name: Forge Deploy

on:
  push:
    branches:
      - main
      - staging
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Set environment (staging)
        if: endsWith(github.ref, '/staging')
        run: |
          echo "ENV=staging" >> $GITHUB_ENV

      - name: Set environment (production)
        if: endsWith(github.ref, '/main') || github.ref_type == 'tag'
        run: |
          echo "ENV=production" >> $GITHUB_ENV

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Composer Install
        run: composer install --no-scripts

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: NPM Install
        run: npm install

      - name: NPM Run Build
        run: npm run build

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          PULSE_ENABLED: false
          TELESCOPE_ENABLED: false
        run: vendor/bin/phpunit

      - name: Deploy Production Site to Forge
        run: |
          composer global require laravel/forge-cli
          forge server:switch ${{ vars.FORGE_PROD_SERVER_NAME }}
          forge deploy ${{ vars.FORGE_PROD_SITE_NAME }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        if: success() && env.ENV == 'production' && github.ref_type == 'tag'

      - name: Deploy Staging Site to Forge
        run: |
          composer global require laravel/forge-cli
          forge server:switch ${{ vars.FORGE_STAGING_SERVER_NAME }}
          forge deploy ${{ vars.FORGE_STAGING_SITE_NAME }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        if: success() && env.ENV == 'staging'
